[package]
name = "cyl_package_tool"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
regex = "1.10.5"
serde = { version = "1.0.204", features = ["derive"] }
serde_derive = "1.0.204"
serde_json = "1.0.120"
toml = "0.8.16"
walkdir = "2.5.0"
